#!/bin/sh

read -p "Enter user to rename : " myname
read -p "Enter new user name : " username
usercheck=$(getent passwd $username)
mynamecheck=$(getent passwd $myname)

if [ -z "$mynamecheck"]
then
    echo "$myname is not listed!"
else
        if [ -z "$usercheck"]
        then
                cd /root
                mkdir -p "Archive"
                cd Archive/
                tar czvf "$myrname".tar.gz /home/"$myname"
                sudo userdel -rf "$myname"
                sudo useradd "$username"
                tar -zxf "$myname".tar.gz /home/"$username"
        else
                echo "$username is already exist!"
fi
fi